global.HARVESTERS_DESIRED = {
    'Markopolis':   1,
    'Stevenopolis': 2,
}
    
global.HARVESTERS_BODY = {
    'Markopolis':   [WORK,WORK,WORK,WORK,WORK,WORK,WORK,WORK,WORK,WORK,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,MOVE,MOVE,MOVE,MOVE],
    'Stevenopolis': [WORK,WORK,WORK,WORK,WORK,WORK,CARRY,CARRY,CARRY,CARRY,CARRY,MOVE,MOVE,MOVE,MOVE,MOVE],
}

global.WALL_STRENGTH = {
    'Markopolis':   WALL_HITS_MAX-128000,
    'Stevenopolis': WALL_HITS_MAX- 66000,
}