global.HARVESTERS_DESIRED = {
    'Markopolis':   1,
    'Stevenopolis': 2,
}
global.UPGRADERS_DESIRED = {
    'Markopolis':   2,
    'Stevenopolis': 2,
}
global.DEFENDERS_DESIRED = {
    'Markopolis':   1,
    'Stevenopolis': 1,
}

global.HARVESTERS_BODY = {
    'Markopolis':   [WORK,WORK,WORK,WORK,WORK,WORK,WORK,WORK,WORK,WORK,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,MOVE,MOVE,MOVE,MOVE],
    'Stevenopolis': [WORK,WORK,WORK,WORK,WORK,WORK,CARRY,CARRY,CARRY,CARRY,CARRY,MOVE,MOVE,MOVE,MOVE,MOVE],
}
global.UPGRADERS_BODY = {
    'Markopolis':   [WORK,WORK,WORK,WORK,WORK,WORK,WORK,WORK,WORK,WORK,WORK,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,MOVE,MOVE,MOVE,MOVE],
    'Stevenopolis': [WORK,WORK,WORK,WORK,WORK,WORK,WORK,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,MOVE,MOVE,MOVE,MOVE,MOVE],
}
global.DEFENDERS_BODY = {
    'Markopolis':   [TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,
                     RANGED_ATTACK,RANGED_ATTACK,RANGED_ATTACK,RANGED_ATTACK,RANGED_ATTACK,RANGED_ATTACK,
                     MOVE,MOVE,MOVE,MOVE,MOVE,MOVE],
    'Stevenopolis': [TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,
                     RANGED_ATTACK,RANGED_ATTACK,RANGED_ATTACK,RANGED_ATTACK,RANGED_ATTACK,RANGED_ATTACK,
                     MOVE,MOVE,MOVE,MOVE,MOVE,MOVE],
}
global.WALL_STRENGTH = {
    'Markopolis':   WALL_HITS_MAX-128000,
    'Stevenopolis': WALL_HITS_MAX- 97000,
}
global.RAMPART_STRENGTH = {
    'W43N2': 10000000-71000,
    'W43N3': 30000000-71000,
}
